name: Main

on:
  push:
    branches: [main, master]
    tags: ['*']
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RADIAN_NO_INPUTHOOK: 1

jobs:
  pytest:
    name: ${{ matrix.os }} r-${{ matrix.r }} py-${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        r: [4.3, latest, devel]
        python: [3.9, 3.12]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: ${{ matrix.python }}
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
      - name: Install required R packages for testing
        run: Rscript -e "install.packages(c('reticulate', 'askpass'))"
      - name: Install and run tests
        run: |
          python -m pip install jedi
          python -m pip install -e .[test]
          pytest -s --coverage
          coverage combine
          coverage xml -i -o coverage.xml
      - name: codecov
        run: |
          python -m pip install codecov
          codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  twine:
    name: Upload tarball
    if: startsWith(github.ref, 'refs/tags/')
    needs: pytest
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
      TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: 3.11
      - run: python -m pip install twine
      - run: python setup.py sdist
      - run: python -m pip install dist/*
      - run: python -m twine upload dist/*
